name: xdggs_dev
channels:
  - conda-forge
dependencies:
  - xarray
  - healpy
  - h5netcdf
  - netcdf4
  - pooch
  - matplotlib-base
  - shapely
  - pytest
  - hypothesis
  - ruff
  - typing-extensions
  - geoarrow-pyarrow
  - lonboard
  # - arro3-core  # not available on macos
  - pip
  - pip:
      - h3ronpy
